### ISSUE TITLE
Turn off email notifications!!

### ISSUE THREAD

**Issue by marieforgue** [w3c/geekweek2020#24]
Too many buttons to choose from the Email or Notifications menus ;) HELP!

**Comment by marieforgue** [comment]
All is said!

**Comment by swickr** [comment]
Two ways, depending on the result you want:
1. Go to your [user account settings](https://github.com/settings/profile) then to notifications and uncheck 'email' in the Watching section.
2. At the top of the page for the repository, there is a button labeled either watch or unwatch.  That button will give you a pulldown list to select unwatch or watch for that one repo.

The first option turns off emails for all the repos in which you may be participating.
The second option only turns off emails for that one repo.
(In your account settings you can also get a list of all repos that you are watching and you can change the watch/unwatch setting in that list.)
